apiVersion: apps/v1           
kind: Deployment              
metadata:
  name: spring    
  labels:                     
    app: twwo
spec:
  replicas: 1                 
  selector:
    matchLabels:              
      app: twwo
  template:                   
    metadata:
      labels:                 
        app: twwo
    spec:                     
      containers:
      - name: spring
        image: spring
        imagePullPolicy: Never
        ports:
          - name: http
            containerPort: 8080 
        resources:
          limits:
            cpu: 0.2
            memory: "200Mi"
---
apiVersion: v1                
kind: Service                 
metadata:                     
  name: spring    
  labels:                     
    app: twwo
spec:                         
  type: NodePort              
  selector:
    app: twwo   
  ports:                      
  - name: http
    port: 8080
    targetPort: 8080